### ISSUE TITLE
fix: unordered peers list

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-opendj#49]
Prior to v4.4, the config that holds peers (in configs layer and serf membership) doesn't respect the order of registered peer.

For illustration:

1. container `ldap` registered as the 1st peer; configs and serf members are ordered properly (`peers=["ldap"]`)
2. container `ldap2` registered as the 2nd peer; config and serf members may ordered (`peers=["ldap", "ldap2"]`) or unordered properly (`peers=["ldap2", "ldap"]`)
3. container `ldap3` registered as the 3rd peer; config and serf members may ordered (`peers=["ldap", "ldap2", "ldap3"]`) or unordered properly (`peers=["ldap2", "ldap", "ldap3"]`)

After investigating the code, there are 2 problems found:

1. casting `set` (where elements are string-based) into `list` doesn't always preserve the order
2. `serf members` output doesn't preserve the order of connected serf agent

The impact of this issue is explained below:

1. given unordered existing list of `peers=["ldap2", "ldap", "ldap3"]`, new container `ldap4` will try to replicate data from `ldap2` first 
2. if `ldap4` unable to replicate from `ldap2` (for various reasons), it will try to replicate from next peer (in this case `ldap`)
3. things are getting complicated if `ldap4` replicate data from problematic peer (out-of-sync)

# Proposed fixes

1. Ensure the peers list is ordered properly (useful for statefulsets)
2. Optionally, add support to specify the source peer priorities (single or comma-separated values) -- for example by adding `GLUU_LDAP_REPL_SOURCES=ldap,ldap3,ldap2` env variable -- to skip the list mentioned above

## Affected versions

* 4.2
* 4.3

**Comment by moabu** [comment]
Since this is for previous versions and this is a discontinued feature >= 4.4 I think we should add an env to allow for the priority of peers to be sorted by the user because in a multi region setup it won't be as easy to sort say `east-opendj-0` and `west-opendj-0` appropiatly given that one may be unhealthy. 


I agree with the proposed fixes which should start with checking the env for user preferred priority then go on on a best effort basis to order the peers list.

There may be an issue with declaring such env because it may be misused by the user. We may attempt to do the following L
1. If the user declares a set of peers that do not exist the peer list will be ordered on a best effort basis based on existing peers.
2. If the user partially declares a set of peers that do exist , order on a best effort basis but giving the users input the priority. Forexample, if the user provided `ldap1`, `ldap0`, `ldap4` and only `ldap3`, `ldap4`, and `ldap5` actually existed the order should be `ldap4`, `ldap3` then `ldap4`.

**Comment by iromli** [comment]
Noted. The feature of peers priority env will be tracked in another GH issue.

**Comment by iromli** [comment]
Implemented in branch 4.2 and 4.3
